language: node_js
node_js:
- '8'
dist: trusty
sudo: required
before_script:
    # - "sudo chown root /opt/google/chrome/chrome-sandbox"
    # - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # give xvfb some time to start
# addons:
#   chrome: stable
cache:
  directories:
  - node_modules
# env:
#     - NODE_ENV=ci
install:
- npm install
script:
- nohup npm run start &
- sleep 3
- npm run test
after_success:
  - echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
  - eval "$(ssh-agent -s)" #start the ssh agent
  - echo -e $ci.pub > ~/.ssh/ci.pub
  - sudo chmod 600 ~/.ssh/*
  - ssh-add ~/.ssh/ci
  - git remote add component oih-playground@git.elastic.io:snazzy-adapter.git
  - git push component master
